language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t 8723150/complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 8723150/complex npm run test -- --coverage

after_success:
  - docker build -t 8723150/multi-client./client
  - docker build -t 8723150/multi-nginx ./nginx
  - docker build -t 8723150/multi-server ./server
  - docker build -t 8723150/multi-worker ./worker

  # LOGIN TO DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # TAKE THOSE IMAGES AND PUSH THEM TO DOCKER HUB
  - docker push 8723150/multi-client 
  - docker push 8723150/multi-nginx
  - docker push 8723150/multi-server
  - docker push 8723150/multi-worker


# deploy:
#   provider: elasticbeanstalk 
#   region: "us-west-2"
#   app: "docker-react"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-west-2-919358087815"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: "$AWS_SECRET_KEY"
